### ISSUE TITLE
[Bug] OpenSearch 2.x not supported in v0.7.2 despite documentation claim

### ISSUE THREAD

**Issue by iParadis** [senacor/elasticsearch-evolution#565]
# Describe the bug
The documentation is misleading. OpenSearch 2.x is not actually supported in version 0.7.2, despite the compatibility matrix stating:

`| elasticsearch-evolution >= 0.7.0 | ... | OpenSearch 1.x - 3.x |`

The root cause is an **HttpClient** version incompatibility:

- Elasticsearch Evolution 0.7.2 uses `elasticsearch-evolution-rest-abstraction-os-restclient` which creates/configures `org.opensearch.client.RestClientBuilder` using **Apache HttpClient 5.x** APIs (`org.apache.hc.core5.http.*`)

- **OpenSearch RestClient 2.x** is built on **Apache HttpClient 4.x** (`org.apache.http.*`)

When Elasticsearch Evolution 0.7.2 attempts to configure the RestClientBuilder with HttpClient 5 classes, it fails because OpenSearch 2.x doesn't have those classes on its classpath.

### Actual compatibility:

- OpenSearch 1.x - 2.x → HttpClient 4.x → Only works with Evolution 0.6.x

- OpenSearch 3.x → HttpClient 5.x → Works with Evolution 0.7.x

### To Reproduce

1. Used Versions:

- Elasticsearch Evolution: 0.7.2
- OpenSearch RestClient: 2.17.1 (my case, same result with newer 2.x versions such 2.19) 
- Java: 17+
- Operating System: Any

2. Configuration:

```
<dependency>
    <groupId>com.senacor.elasticsearch.evolution</groupId>
    <artifactId>elasticsearch-evolution-core</artifactId>
    <version>0.7.2</version>
</dependency>
<dependency>
    <groupId>com.senacor.elasticsearch.evolution</groupId>
    <artifactId>elasticsearch-evolution-rest-abstraction-os-restclient</artifactId>
    <version>0.7.2</version>
</dependency>
<dependency>
    <groupId>org.opensearch.client</groupId>
    <artifactId>opensearch-rest-client</artifactId>
    <version>2.17.1</version>
</dependency>
```

3. Infrastructure:

- OpenSearch Server 2.17.1 (or 2.19.x)

4. Error Message:
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.senacor.elasticsearch.evolution.core.ElasticsearchEvolution]: Factory method 'opensearchEvolution' threw exception with message: org/apache/hc/core5/http/ParseException
        ...
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ParseException
        at com.mirakl.connect.catalog.outbound.configuration.OpensearchOutboundMigrationConfiguration.opensearchEvolution(OpensearchOutboundMigrationConfiguration.java:32)
        ...
Caused by: java.lang.ClassNotFoundException: org.apache.hc.core5.http.ParseException
```

# Expected behavior
One of the following should be true:
1. **Option A (Preferred):** OpenSearch 2.x should work out of the box with `elasticsearch-evolution-rest-abstraction-os-restclient:0.7.2`
2. **Option B**: Documentation should clearly state:

- `0.6.x` → OpenSearch 1.x - 2.x (HttpClient 4)
- `0.7.x` → OpenSearch 3.x only (HttpClient 5)

3. Option C: Provide a separate artifact like:

- elasticsearch-evolution-rest-abstraction-os-restclient-v2 (for OpenSearch 2.x / HttpClient 4)
- elasticsearch-evolution-rest-abstraction-os-restclient-v3 (for OpenSearch 3.x / HttpClient 5)

## Additional context

The README states:

> "OpenSearch RestClient implementation: `EvolutionOpenSearchRestClient` which is designed for OpenSearch 2.x"

This suggests OpenSearch 2.x should work, but it fundamentally cannot due to the HttpClient version mismatch.

# Workaround:

Currently, users must downgrade to Elasticsearch Evolution 0.6.1 to use OpenSearch 2.x:
```
<dependency>
    <groupId>com.senacor.elasticsearch.evolution</groupId>
    <artifactId>elasticsearch-evolution-core</artifactId>
    <version>0.6.1</version>
</dependency>
```

or create their own RestClient based on http4
- use core to create custom **EvolutionRestClient** as stated in documentation
```
        <dependency>
            <groupId>com.senacor.elasticsearch.evolution</groupId>
            <artifactId>elasticsearch-evolution-core</artifactId>
            <version>${elasticsearch.evolution.version}</version>
        </dependency>
        <dependency>
            <groupId>com.senacor.elasticsearch.evolution</groupId>
            <artifactId>elasticsearch-evolution-rest-abstraction-os-restclient</artifactId>
            <version>${elasticsearch.evolution.version}</version>
        </dependency>
```
- code sample
```
    @Bean
    ElasticsearchEvolution opensearchEvolution(
            ElasticsearchEvolutionConfig config, org.opensearch.client.RestClient restClient) {
        return config.load(new OpenSearch2xEvolutionRestClient(restClient));
    }

private record OpenSearch2xEvolutionRestClient(RestClient restClient) implements EvolutionRestClient {

        @Override
        public String info() {
            return "Custom OpenSearch 2.x RestClient (HttpClient 4.x)";
        }

        @Override
        public EvolutionRestResponse execute(
                HttpMethod method,
                String endpoint,
                Map<String, String> headers,
                Map<String, String> urlParams,
                String body)
                throws IOException {

            Request request = new Request(method.name(), endpoint);

            // Add URL parameters
            if (urlParams != null) {
                urlParams.forEach(request::addParameter);
            }

            // Add body
            if (body != null && !body.isEmpty()) {
                request.setJsonEntity(body);
            }

            // Execute request
            Response response = restClient.performRequest(request);

            // Convert to EvolutionRestResponse
            return new EvolutionRestResponseImpl(
                    response.getStatusLine().getStatusCode(),
                    Optional.empty(),
                    Optional.of(new String(response.getEntity().getContent().readAllBytes(), StandardCharsets.UTF_8)));
        }
    } 
```

**Comment by xtermi2** [comment]
@iParadis can you please try out version [0.7.3-SNAPSHOT](https://github.com/senacor/elasticsearch-evolution/releases/tag/0.7.3-SNAPSHOT-2026-01-16T19-57-42-8c5a972) from this snapshot repositry (see also [consuming-snapshot-releases-for-your-project](https://central.sonatype.org/publish/publish-portal-snapshots/#consuming-snapshot-releases-for-your-project))
```xml
<repositories>
  <repository>
    <name>Central Portal Snapshots</name>
    <id>central-portal-snapshots</id>
    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by xtermi2** [comment]
thanks for testing, then I will do a release tonight
